PYTHON = /usr/bin/python

all: test

test:
	$(PYTHON) chardet-c-detector.py
	$(PYTHON) chardet-compatible-basic.py
	$(PYTHON) chardet-c-init-detect-close.py
	$(PYTHON) chardet-compatible-incrementally.py
	$(PYTHON) chardet-compatible-multiple-files.py
